import {useState, useEffect} from 'react'
import Head from 'next/head'
import Product from '../components/Product'

export const getStaticProps = async () => {
  const res = await fetch('https://fakestoreapi.com/products');
  const data = await res.json();
  return{
    props: {products: data}
  }
}


export default function Home({products}) {

  const [filter, setFilter] = useState([])
  const [search, setSearch] = useState('')

  useEffect((e) => {
    if(search === ''){
      setFilter(products)
    } else {
      setFilter(products.filter((product) => product.title.toLowerCase().includes(search.toLowerCase())))
    }
  }, [products, search])

  const handleSearch = (e) => {
    setSearch(e.target.value)
  }

  return (
    <div className='container'>
      <Head>
        {/* <title>Create Next App</title> */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row">
        <div className="col-12">
          <h1>hello from next</h1>
          <input className="form-control mb-3" type="text" placeholder="Search for a product" aria-label="Search for a product" value={search} onChange={handleSearch} />
        </div>

      {filter.map((product, index) => (
        <div className="col-3" key={index} >
          <Product product={product} />
        </div>
      ))}
      </div>
    </div>
  )
}
